--- # 端口 正式环境
server:
  port: 8081
#  ssl:
#    key-store: classpath:4183142_iazuresky.com.pfx
#    key-store-password: HIKfLP4b
--- #数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池配置
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j2
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置监控服务器
      stat-view-servlet:
        url-pattern: /druid/*
        login-username: admin
        login-password: root
        reset-enable: false
        # 添加IP白名单
        #allow:
        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
        #deny:
      web-stat-filter:
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.jpeg,*.png,*.css,*.ico,/druid/*"
      url: jdbc:mysql://localhost:3306/vspringblog?characterEncoding=utf8&serverTimezone=GMT%2B8&allowMultiQueries=true&autoReconnect=true
      username: root
      password: zaq123
    ## 数据库配置 - end
    driver-class-name: com.mysql.jdbc.Driver


--- #mybatis plus设置
mybatis-plus:
  type-aliases-package: com.whyzaa.vspringblog.entity
  mapper-locations: classpath:sqlmapper/*.xml
  global-config:
    banner: false
    db-config:
      #主键类型
      id-type: auto
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
--- #日志配置
logging:
  file:
    max-size: 100MB # 最大日志文件大小
    max-history: 15 # 日志保存15天
    total-size-cap: 200MB # 日志备份的总大小
  config: classpath:logbak-spring.xml
--- #redis缓存配置
spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 2
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6479
    # Redis服务器连接密码（默认为空）
    password: Ls892903912
    # 连接超时时间（毫秒）默认是2000ms
    timeout: 5s
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接
